os: osx

before_install:
- brew update
- brew install sassc

install: true

script:
- make STYLE_HREF="<link rel=\\\"stylesheet\\\" href=\\\"https:\\\/\\\/tracsa.github.io\\\/vi-xml\\\/proceso_style.css\\\"\\\/>"

deploy:
- provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  on:
    branch: master
